version: "3.8"

services:
  authenticationDatabase:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      timeout: 10s
      retries: 40
      start_period: 25s
    networks:
      - authenticationNetwork
  storeDatabase:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      timeout: 10s
      retries: 40
      start_period: 25s
    networks:
      - storeNetwork
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - authenticationNetwork
      - storeNetwork
  authenticationDatabaseMigration:
    image: authenticationdatabasemigration
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      authenticationDatabase:
        condition: service_healthy
    networks:
      - authenticationNetwork
  storeDatabaseMigration:
    image: storedatabasemigration
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storeDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      storeDatabase:
        condition: service_healthy
    networks:
      - storeNetwork
  authentication:
    image: authentication
    ports:
      - "5000:5000"
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - authenticationDatabaseMigration
    networks:
      - authenticationNetwork
  owner:
    image: owner
    ports:
      - "5001:5001"
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storeDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - storeDatabaseMigration
    networks:
      - storeNetwork
  customer:
    image: customer
    ports:
      - "5002:5002"
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storeDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - storeDatabaseMigration
    networks:
      - storeNetwork
  courier:
    image: courier
    ports:
      - "5003:5003"
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storeDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - storeDatabaseMigration
    networks:
      - storeNetwork

networks:
  authenticationNetwork:
  storeNetwork: