version: "3.8"

services:
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  storeDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
  authenticationAdminer:
    image: adminer
    ports:
      - "8080:8080"
  storeAdminer:
    image: adminer
    ports:
      - "8081:8080"