version: "3.8"

services:
  authenticationDatabase:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  authenticationDatabaseMigration:
    image: authenticationdatabasemigration
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      authenticationDatabase:
        condition: service_healthy
  authentication:
    image: authentication
    ports:
      - "5000:5000"
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - authenticationDatabaseMigration