version: "3.8"

services:
  storeDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
  adminer:
    image: adminer
    ports:
      - "8081:8080"